// Sample data for videos
export const sampleVideos = [
  {
    videoId: "video01",
    title: "Learn React in 30 Minutes",
    thumbnail: "/placeholder.svg?height=200&width=360&text=Learn%20React",
    description:
      "A quick tutorial to get started with React. This video covers the basics of components, props, state, and hooks. Perfect for beginners who want to learn React quickly.",
    channelId: "channel01",
    channelName: "CodeMaster",
    uploader: "user01",
    views: 15200,
    likes: 1023,
    dislikes: 45,
    uploadDate: "2024-09-20",
    comments: [
      {
        commentId: "comment01",
        userId: "user02",
        username: "ReactFan",
        text: "Great video! Very helpful for beginners.",
        timestamp: "2024-09-21T08:30:00Z",
      },
      {
        commentId: "comment02",
        userId: "user03",
        username: "WebDev123",
        text: "I've been struggling with React for weeks, and this video cleared up so many concepts for me. Thank you!",
        timestamp: "2024-09-22T14:15:00Z",
      },
    ],
  },
  {
    videoId: "video02",
    title: "Build a Full Stack App with Next.js, TypeScript and MongoDB",
    thumbnail: "/placeholder.svg?height=200&width=360&text=Full%20Stack%20App",
    description:
      "In this comprehensive tutorial, we'll build a complete application using Next.js, TypeScript, and MongoDB. Learn how to create API routes, connect to a database, and deploy your application.",
    channelId: "channel02",
    channelName: "FullStackDev",
    uploader: "user04",
    views: 8700,
    likes: 742,
    dislikes: 12,
    uploadDate: "2024-09-15",
    comments: [
      {
        commentId: "comment03",
        userId: "user05",
        username: "NextJSLover",
        text: "This is exactly what I needed! Great explanation of the MERN stack.",
        timestamp: "2024-09-16T10:45:00Z",
      },
    ],
  },
  {
    videoId: "video03",
    title: "CSS Grid Layout Tutorial",
    thumbnail: "/placeholder.svg?height=200&width=360&text=CSS%20Grid",
    description:
      "Master CSS Grid Layout with this comprehensive tutorial. Learn how to create responsive layouts with ease.",
    channelId: "channel03",
    channelName: "CSSMaster",
    uploader: "user06",
    views: 12400,
    likes: 890,
    dislikes: 15,
    uploadDate: "2024-09-10",
    comments: [],
  },
  {
    videoId: "video04",
    title: "JavaScript ES6 Features You Need to Know",
    thumbnail: "/placeholder.svg?height=200&width=360&text=JavaScript%20ES6",
    description:
      "Explore the most important ES6 features that every JavaScript developer should know. This video covers arrow functions, destructuring, spread/rest operators, and more.",
    channelId: "channel01",
    channelName: "CodeMaster",
    uploader: "user01",
    views: 18900,
    likes: 1245,
    dislikes: 32,
    uploadDate: "2024-09-05",
    comments: [],
  },
  {
    videoId: "video05",
    title: "Building a YouTube Clone with React",
    thumbnail: "/placeholder.svg?height=200&width=360&text=YouTube%20Clone",
    description:
      "Learn how to build a YouTube clone using React, Firebase, and Material UI. This project-based tutorial will teach you real-world application development.",
    channelId: "channel04",
    channelName: "ReactProjects",
    uploader: "user07",
    views: 22300,
    likes: 1876,
    dislikes: 41,
    uploadDate: "2024-08-28",
    comments: [],
  },
  {
    videoId: "video06",
    title: "TypeScript Crash Course for Beginners",
    thumbnail: "/placeholder.svg?height=200&width=360&text=TypeScript",
    description:
      "Get up to speed with TypeScript in this beginner-friendly crash course. Learn types, interfaces, generics, and more.",
    channelId: "channel05",
    channelName: "TypeScriptGuru",
    uploader: "user08",
    views: 9800,
    likes: 823,
    dislikes: 17,
    uploadDate: "2024-09-18",
    comments: [],
  },
  {
    videoId: "video07",
    title: "Node.js Authentication with JWT",
    thumbnail: "/placeholder.svg?height=200&width=360&text=Node.js%20Auth",
    description:
      "Learn how to implement JWT authentication in your Node.js applications. This tutorial covers user registration, login, and protected routes.",
    channelId: "channel06",
    channelName: "BackendDev",
    uploader: "user09",
    views: 7600,
    likes: 612,
    dislikes: 8,
    uploadDate: "2024-09-12",
    comments: [],
  },
  {
    videoId: "video08",
    title: "Responsive Web Design Principles",
    thumbnail: "/placeholder.svg?height=200&width=360&text=Responsive%20Design",
    description:
      "Master the principles of responsive web design. Learn how to create websites that look great on all devices.",
    channelId: "channel03",
    channelName: "CSSMaster",
    uploader: "user06",
    views: 14500,
    likes: 1032,
    dislikes: 21,
    uploadDate: "2024-09-08",
    comments: [],
  },
]
